# nginx docker compose

version: '3'

services: 
    nginx:
        image: nginx:latest
        container_name: webmob-nginx
        ports:
            - 8080:80
        volumes:
            - ./public:/usr/share/nginx/html